// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggG-1W1QNtLz4S22tQM7sVts9Cvy2d7c',
    appId: '1:275626497484:web:b793cc75656e5d09e53969',
    messagingSenderId: '275626497484',
    projectId: 'safeguard-system-7f787',
    authDomain: 'safeguard-system-7f787.firebaseapp.com',
    storageBucket: 'safeguard-system-7f787.firebasestorage.app',
    measurementId: 'G-865HG8WC79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4iSEjXN_hNc0sbBnVWGTzolwaHe1O1k',
    appId: '1:275626497484:android:d9b7b7f1b32cadbae53969',
    messagingSenderId: '275626497484',
    projectId: 'safeguard-system-7f787',
    storageBucket: 'safeguard-system-7f787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNGsOH1oidh89aLrDf9p1Yxi3cGwRBLhQ',
    appId: '1:275626497484:ios:6f4456c8d1e5240be53969',
    messagingSenderId: '275626497484',
    projectId: 'safeguard-system-7f787',
    storageBucket: 'safeguard-system-7f787.firebasestorage.app',
    androidClientId: '275626497484-pv8k5hnolkqvnmqd2mjbsu71sc9bidug.apps.googleusercontent.com',
    iosClientId: '275626497484-uv7n0pke8vqeoeslpvh68skq9igucsrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNGsOH1oidh89aLrDf9p1Yxi3cGwRBLhQ',
    appId: '1:275626497484:ios:6f4456c8d1e5240be53969',
    messagingSenderId: '275626497484',
    projectId: 'safeguard-system-7f787',
    storageBucket: 'safeguard-system-7f787.firebasestorage.app',
    androidClientId: '275626497484-pv8k5hnolkqvnmqd2mjbsu71sc9bidug.apps.googleusercontent.com',
    iosClientId: '275626497484-uv7n0pke8vqeoeslpvh68skq9igucsrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggG-1W1QNtLz4S22tQM7sVts9Cvy2d7c',
    appId: '1:275626497484:web:b793cc75656e5d09e53969',
    messagingSenderId: '275626497484',
    projectId: 'safeguard-system-7f787',
    authDomain: 'safeguard-system-7f787.firebaseapp.com',
    storageBucket: 'safeguard-system-7f787.firebasestorage.app',
    measurementId: 'G-865HG8WC79',
  );
}
